POST http://localhost:3001/api/blogs
content-Type: application/json

{
        "title": "new Blog",
        "author": "me",
        "url": "http://example.com"
}

###

GET http://localhost:3001/api/blogs